Models/Cart.cs
namespace TheWaterProject2.Models;

public class Cart
{
    public List<CartLine> Lines { get; set; } = new List<CartLine>();

    public void AddItem(Project proj, int quantity)
    {
        CartLine? Line = Lines
            .Where(x => x.Project.ProjectId == proj.ProjectId)
            .FirstOrDefault();
        
        // Has this item already been added to the cart
        if (Line == null)
        {
            Lines.Add(new CartLine
            {
                Project = proj,
                Quantity = quantity
            });
        }
        else
        {
            Line.Quantity += quantity;
        }
    }

    public void RemoveLine(Project proj) => Lines.RemoveAll(x => x.Project.ProjectId == proj.ProjectId);

    public void Clear() => Lines.Clear();

    public Decimal CalculateTotal() => Lines.Sum(x => 25 * x.Quantity);
        
    public class CartLine
    {
        public int CartLineId { get; set; }
        public Project Project { get; set; }
        public int Quantity { get; set; }
    }    
}

Models/EFWaterRepository.cs
namespace TheWaterProject2.Models
{
    public class EFWaterRepository : IWaterRepository
    {
        private WaterProjectContext _context;
        public EFWaterRepository(WaterProjectContext temp) { 
            _context = temp;    
        } //constructor
        public IQueryable<Project> Projects => _context.Projects;
    }
}

Models/ErrorViewModel.cs
namespace TheWaterProject2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/IWaterRepository.cs
namespace TheWaterProject2.Models
{
    //interface
    public interface IWaterRepository
    {
        public IQueryable<Project> Projects { get; }    
    }
}

Models/Project.cs
using System.ComponentModel.DataAnnotations;

namespace TheWaterProject2.Models
{
    public class Project
    {
        [Key]
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string ProgramName { get; set; }
        public string? ProjectType { get; set; }
        public int ProjectImpact { get; set; }
        public DateTime ProjectInstallation { get; set; }
        public string ProjectPhase { get; set; }    
    }
}

Models/ViewModels/PaginationInfo.cs
namespace TheWaterProject2.Models.ViewModels
{
    public class PaginationInfo
    {

        //keep track of how many items and how many per page
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }    
        public int TotalPages => (int) (Math.Ceiling((decimal) TotalItems / ItemsPerPage));
    }
}

Models/ViewModels/ProjectsListViewModel.cs
namespace TheWaterProject2.Models.ViewModels
{
    public class ProjectsListViewModel
    {
        public IQueryable<Project> Projects { get; set;}
        public PaginationInfo PaginationInfo { get; set;} = new PaginationInfo();
        public string? CurrentProjectType { get; set; }
    }
}

Models/WaterProjectContext.cs
using Microsoft.EntityFrameworkCore;

namespace TheWaterProject2.Models
{
    public class WaterProjectContext : DbContext
    {
        public WaterProjectContext(DbContextOptions<WaterProjectContext> options) : base(options) { }

        public DbSet<Project> Projects { get; set; }
    }
}

Components/ProjectsTypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TheWaterProject2.Models;

namespace TheWaterProject2.Components;

// this is used to get the filter feature
public class ProjectsTypesViewComponent : ViewComponent
{
    private IWaterRepository _waterRepo;
    
    //access the database through repository. Constructor
    public ProjectsTypesViewComponent(IWaterRepository temp)
    {
        _waterRepo = temp;
    }
    public IViewComponentResult Invoke()
    {
        ViewBag.SelectedProjectType = RouteData?.Values["projectType"];
        
        var projectTypes = _waterRepo.Projects
            .Select(x => x.ProjectType)
            .Distinct()
            .OrderBy(x => x);
        
        return View(projectTypes);
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TheWaterProject2.Models;
using TheWaterProject2.Models.ViewModels;

namespace TheWaterProject2.Controllers
{
    public class HomeController : Controller
    {
        private IWaterRepository _repo;

        public HomeController(IWaterRepository temp)
        {
            _repo = temp;
        }

        //dont name it page. name var pageNum
        // this is used for pagination. doing 5 records per page
        public IActionResult Index(int pageNum,string? projectType)
        {

            int pageSize = 2;

            var blah = new ProjectsListViewModel
            {
                Projects = _repo.Projects
                    .Where(x => x.ProjectType == projectType || projectType == null)
                    .OrderBy(x => x.ProjectName)
                    .Skip((pageNum - 1) * pageSize)
                    .Take(pageSize),

                PaginationInfo = new PaginationInfo
                {
                    CurrentPage = pageNum,
                    ItemsPerPage = pageSize,
                    TotalItems = projectType == null ? _repo.Projects.Count() : _repo.Projects.Where(x => x.ProjectType == projectType).Count()
                },
                
                CurrentProjectType = projectType
            };

            return View(blah);
        }

    }
}

Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TheWaterProject2.Infrastructure;
using TheWaterProject2.Models;

namespace TheWaterProject2.Pages;

public class CartModel : PageModel
{
    private IWaterRepository _repo;
    public CartModel(IWaterRepository temp)
    {
        _repo = temp;
    }
    public Cart? Cart { get; set; }
    public string ReturnUrl { get; set; } = "/";
    public void OnGet(string returnUrl)
    {
        ReturnUrl = returnUrl ?? "/";
        Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
    }

    public IActionResult OnPost(int projectId, string returnUrl)
    {
        Project proj = _repo.Projects
            .FirstOrDefault(x => x.ProjectId == projectId);

        if (proj != null)
        {
            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
            Cart.AddItem(proj, 1);
            HttpContext.Session.SetJson("cart", Cart);
        }

        return RedirectToPage(new { returnUrl = returnUrl });
    }
}

Pages/Cart.cshtml
@page
@using Microsoft.EntityFrameworkCore
@model TheWaterProject2.Pages.CartModel


<h2>Your Cart</h2>

<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th>Project Name:</th>
        <th>Quantity</th>
        <th class="text-right">Amount</th>
        <th class="text-right">Subtotal</th>
    </tr>
    </thead>
    
    <tbody>
    @foreach (var l in Model.Cart?.Lines ?? Enumerable.Empty<Models.Cart.CartLine>())
    {
        <tr>
            <td class="text-left">@l.Project.ProjectName</td>
            <td class="text-center">@l.Quantity</td>
            <td class="text-right">$25</td>
            <td class="text-right">@((l.Quantity * 25).ToString("c"))</td>
        </tr>
    }
    </tbody>
    
    <tfoot>
    <tr>
        <td colspan="3" class="text-right">Total:</td>
        <td class="text-right">@Model.Cart?.CalculateTotal().ToString("c")</td>
    </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Donating</a>
</div>

Pages/_CartLayout.cshtml
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>The Water Project</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>

<body>
<div class="bg-dark text-white p-2">
    <span class="navbar-brand m-lg-2">THE WATER PROJECT</span>
</div>

<div class="m-1 p-1">
    @RenderBody()
</div>

</body>
</html>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model ProjectsListViewModel

    <h1>Water Project</h1>

    
    @foreach (Project p in Model.Projects)
    {      
       <partial name="ProjectSummary" model="p" />
        
    }

<div page-model="@Model.PaginationInfo" page-action="Index" page-classes-enabled="true" page-class="btn" 
     page-class-normal="btn-outline-dark" page-class-selection="btn-primary" page-url-projectType="@Model.CurrentProjectType" 
     class="btn-group pull-right m-1"></div>


@*     Links to navigate through the pages.
 *@    
    @* <a asp-controller="Home" asp-action="Index" asp-route-pageNum="1">1</a>
    <a asp-controller="Home" asp-action="Index" asp-route-pageNum="2">2</a>
    <a asp-controller="Home" asp-action="Index" asp-route-pageNum="3">3</a> *@

Views/Shared/Components/ProjectsTypes/Default.cshtml
@model IEnumerable<string>

<div class="d-grid gap-2">
    <a class="btn btn-outline-secondary" asp-controller="Home" asp-action="Index" asp-route-projectType="" asp-route-pageNum="">Home</a>
    @foreach (string pt in Model ?? Enumerable.Empty<string>())
    {
        // pass in the data to what to query
        // what project type are we using
        <a class="btn @(pt == ViewBag.SelectedProjectType ? "btn-primary" : "btn-outline-secondary")" asp-controller="Home" asp-action="Index" asp-route-projectType="@pt" asp-route-pageNum="1">@pt</a>
    }
</div>

Views/Shared/ProjectSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@using TheWaterProject2.Infrastructure
@model Project 

<div class="card m-1 p-1">
    <h4>
        @Model.ProjectName
        <span class="badge rounded-pill bg-primary text-white float-end"><small>@Model.ProjectImpact</small></span>
    </h4>

    <ul>
        <li>Project Type: @Model.ProjectType</li>
        <li>Program: @Model.ProgramName</li>
        <li>Installation: @Model.ProjectInstallation</li>
        <li>Phase: @Model.ProjectPhase</li>
    </ul>
    <form id="@Model.ProjectId" method="post" asp-page="/Cart">
        <input type="hidden" asp-for="@Model.ProjectId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()"/>
        <button type="submit" class="btn-outline-success btn-sm float-end">Donate</button>
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TheWaterProject2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TheWaterProject2.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand m-lg-2">THE WATER PROJECT</span>
    </div>
    <div class="row m-1 p-1">
        <div class="col-3">
            <vc:projects-types />
        </div>
        <div class="container col-9">
          <main role="main" class="pb-3">
              @RenderBody()
          </main>
      </div>
    </div>

    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TheWaterProject2 - <a asp-area="" asp-controller="Home">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>